@hostname = api.example.com
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = image/svg+xml

###
// Simple diagram with some options
POST http://localhost:8080/render HTTP/1.1
content-type: image/svg+xml

{
    "options": {
        "pad": "0",
        "sketch": "true"
    },
    "content": "Server -> Client"
}

### 
// Complex diagram with steps
POST http://localhost:8080/render HTTP/1.1
content-type: image/svg+xml

{
    "options": {
        "bundle": "true",
        "animate-interval": "1000"
    },
    "content": "steps: { 1: { Approach road }\n2: { Approach road -> Cross road }\n3: { Cross road -> Make you wonder why } }"
}


